package LX;

/* Generated By:JavaCC: Do not edit this line. XML_parserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XML_parserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int XML_DECL = 7;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int COMMENT = 9;
  /** RegularExpression Id. */
  int DOCTYPE = 10;
  /** RegularExpression Id. */
  int CLOSE_START = 11;
  /** RegularExpression Id. */
  int SELF_CLOSE = 12;
  /** RegularExpression Id. */
  int OPEN = 13;
  /** RegularExpression Id. */
  int CLOSE = 14;
  /** RegularExpression Id. */
  int NAME = 15;
  /** RegularExpression Id. */
  int EQUALS = 16;
  /** RegularExpression Id. */
  int STRING = 17;
  /** RegularExpression Id. */
  int CHARACTER_DATA = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\ufeff\"",
    "<XML_DECL>",
    "<SINGLE_LINE_COMMENT>",
    "<COMMENT>",
    "<DOCTYPE>",
    "\"</\"",
    "\"/>\"",
    "\"<\"",
    "\">\"",
    "<NAME>",
    "\"=\"",
    "<STRING>",
    "<CHARACTER_DATA>",
  };

}
