package LX;

/* Generated By:JavaCC: Do not edit this line. XML_parserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XML_parserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int XML_DECL = 6;
  /** RegularExpression Id. */
  int COMMENT = 7;
  /** RegularExpression Id. */
  int DOCTYPE = 8;
  /** RegularExpression Id. */
  int CLOSE_START = 9;
  /** RegularExpression Id. */
  int SELF_CLOSE = 10;
  /** RegularExpression Id. */
  int OPEN = 11;
  /** RegularExpression Id. */
  int CLOSE = 12;
  /** RegularExpression Id. */
  int NAME = 13;
  /** RegularExpression Id. */
  int EQUALS = 14;
  /** RegularExpression Id. */
  int STRING = 15;
  /** RegularExpression Id. */
  int CHARACTER_DATA = 16;
  /** RegularExpression Id. */
  int END_OF_FILE = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<XML_DECL>",
    "<COMMENT>",
    "<DOCTYPE>",
    "\"</\"",
    "\"/>\"",
    "\"<\"",
    "\">\"",
    "<NAME>",
    "\"=\"",
    "<STRING>",
    "<CHARACTER_DATA>",
    "\"\"",
  };

}
